version: '3.7'

services:
  raspotify:
    image: flo2104/raspotify-docker:latest
    container_name: raspotify
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./default_raspotify:/etc/default/raspotify
    environment:
      - SPOTIFY_NAME=MyRaspotifyDevice
      - SPOTIFY_BITRATE=160
    ports:
      - "4000:4000"
