services:
  raspotify:
    image: flo2104/raspotify_docker:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - DEVICE_NAME=FloRaspotify
      # Optional: Uncomment and configure if needed
      # - BITRATE=160
      # - OPTIONS=--username your_spotify_username --password your_spotify_password
    volumes: []
